addons:
  hosts:
    - pmg.test
services:
  - docker
script:
  - "docker-compose run --rm web nosetests tests"
  - "docker-compose run --rm web python setup_dev_database.py"
  - "docker-compose run --rm web python app.py db stamp head"
  - "docker-compose run --rm web python index_elastic.py"
  - "docker-compose up -d"
  - bin/wait-for-app.sh
  - curl -f http://pmg.test:5000 | grep "Featured Content"
