language: python
python:
  - "2.7"
addons:
  postgresql: "9.4"
env:
  - DATABASE_URL=postgres://postgres:@localhost:5432/pmg_test
before_script:
  - psql -c 'create database pmg_test;' -U postgres
install: 
  - "pip install -r requirements.txt"
script: nosetests tests
