version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: pmg_flask
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      - DATABASE_SERVER_NAME=postgres
    ports:
      - "5000:5000"
    command: python app.py runserver
    extra_hosts:
      - "api.pmg.test:127.0.0.1"
      - "pmg.test:127.0.0.1"

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=pmg
      - POSTGRES_DB=pmg
      - POSTGRES_PASSWORD=pmg
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5431:5432"

volumes:
  db-data: